#!/bin/sh

docker run -ti \
       --mount type=bind,src=/Users/pg/repo/packages,dst=/distro/repo \
       --mount type=bind,src=/Users/pg/NewHope/newhope/plugins,dst=/distro/plugins \
       --env TARGET=$1 \
       $2

#antonsamokhvalov/newhope:latest
