#!/usr/bin/python

import sys

sys.dont_write_bytecode = True

import os
import signal
import Queue


__file__ = os.path.abspath(__file__)
signal.signal(signal.SIGPIPE, signal.SIG_IGN)


def real_main():
   file_data = None
   data = None
   #REPLACEME

   if not data:
      with open(os.path.dirname(__file__) + '/upm/stagea.py') as f:
         data = f.read()

   qq = Queue.Queue()      

   args = {'qq': qq, 'where': __file__, 'data': file_data}
   ctx = {'args': args}
   exec compile(data +'\nmain(args, **args)\n', '__main__', 'exec') in ctx
   ctx.clear()

   while True:
      try:
         qq.get()()
      except StopIteration:
         break

   raise SystemExit(0)


if __name__ == '__main__':
    real_main()
