#!/usr/bin/env python
## install_me

import os
import sys


def install_hook():
   STDERR = sys.stderr

   def excepthook(*args):
      print >>STDERR, 'caught'
      print >>STDERR, args

   sys.excepthook = excepthook

# install_hook()
sys.dont_write_bytecode = True


try:
   from upm_cli import run_main
except ImportError:
   sys.path.append(os.path.dirname(os.path.abspath(__file__)))

   from upm.cli import run_main


if __name__ == '__main__':
   sys.exit(run_main())
