#!/usr/bin/env python2

import os
import sys
import random
import fcntl


def install(to, func):
    if not os.path.exists(to):
	with open('/runtime/Makefile', 'r') as f:
            fcntl.flock(f.fileno(), fcntl.LOCK_EX)
            
            try:
        	if os.path.exists(to):
            	    return to
            
		tmp = to + '_' + str(int(random.random() * 10000000))
		func(tmp)
		os.rename(tmp, to)
	    finally:
		fcntl.flock(f.fileno(), fcntl.LOCK_UN)
		
    return to


for pkg in sys.argv[1:]:
    def do(to):
	os.makedirs(to)
        os.system('tar -xf /repo/' + pkg + ' -C ' + to)

    path = install('/managed/' + pkg[:pkg.find('.tar.')], do)
    os.symlink(path, os.path.abspath(os.getcwd()) + '/' + os.path.basename(path))
