#!/bin/sh

get_file() {
  curl --remote-name "$1" || \
  wget --passive-ftp "$1" || \
  wget "$1" || \
  ftp "$1" </dev/null || \
  exit 1
}

get_file $1
p=`basename $1`
tar --strip-components 1 -xf $p 
#rm $p
