def common_distr():
    return [
        'superbox',
        'mc-slang',
        'yash',
        'bash',
        'dash',
        'p7zip',
        'unrar',
        'bsdtar',
        'python3',
        'xz',
        'cmake',
        'curl',
        'bzip2',
        'openssl',
        'diffutils',
        'file',
        'gawk',
        'grep',
        'gzip',
        'make',
        'ninja',
        'pkg-config',
        'sed',
    ]
